[dev_sql_servers]
# The format: [server_name].database.windows.net
sql-dev-day2-lab-7u79mu5l.database.windows.net

[prod_sql_servers]
# The format: [server_name].database.windows.net
sql-prod-day2-lab-79gscxzm.database.windows.net